version: "2.2"
services:
  app:
    build: .
    volumes:
      - .:/navanplants
    ports:
      - 8000:8000
    image: navanplants:navanplants_image
    container_name: navanplants_container
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - "postgres:/data/postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

volumes:
  postgres:
