version: "2.4"
services:
  app:
    build: .
    volumes:
      - .:/navanplants
    ports:
      - 8000:8000
    image: navanplants:navanplants_image
    container_name: navanplants_container
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
  db:
    image: postgres
    volumes:
      - "postgres:/data/postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
    networks:
      - djangonetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres:

networks:
  djangonetwork:
    driver: bridge
    external: true  
