# Generated by Django 5.0.6 on 2024-06-01 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                (
                    "friendly_name",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=254, null=True)),
                ("name", models.CharField(max_length=254)),
                ("description", models.TextField(max_length=1000)),
                (
                    "has_sizes",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plants.category",
                    ),
                ),
            ],
        ),
    ]
