# Generated by Django 5.0.4 on 2024-05-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
